# Generated by Django 5.0.4 on 2024-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RainfallPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.FloatField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
