# Generated by Django 4.2.11 on 2024-04-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='language',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='recording_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
